In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'], 'max_features': ['auto', 'sqrt', 'log2'], 'n_estimators': [10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81704773 0.83303495 0.82238359 0.83272042
        nan        nan 0.81127034 0.83376749 0.81803902 0.83487091
        nan        nan 0.81766428 0.83418671 0.81912163 0.83275338
        nan        nan 0.82120939 0.83202424 0.81661991 0.83285974]
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}

In [8]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002339,0.000298,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002388,0.000642,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.061886,0.008647,0.007071,0.001518,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844567,0.762340,0.851233,0.802019,0.825080,0.817048,0.032278,14
3,0.452042,0.009275,0.021868,0.002371,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857075,0.780896,0.861923,0.824801,0.840480,0.833035,0.029169,4
4,0.062197,0.006624,0.008736,0.003732,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844298,0.770435,0.846150,0.821048,0.829986,0.822384,0.027580,9
5,0.433518,0.009539,0.021748,0.004295,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.854995,0.782126,0.861410,0.825298,0.839774,0.832720,0.028227,7
6,0.002222,0.001551,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001712,0.000287,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.137772,0.003296,0.005580,0.000721,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.835799,0.743821,0.849391,0.794334,0.833007,0.811270,0.038376,16
9,1.368245,0.032358,0.019564,0.001910,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854326,0.785582,0.855111,0.828737,0.845081,0.833767,0.025897,3
10,0.147635,0.013420,0.004938,0.000336,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.844797,0.763337,0.841200,0.808225,0.832636,0.818039,0.030180,12
11,1.356478,0.015489,0.018410,0.000754,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857617,0.786639,0.857184,0.829176,0.843739,0.834871,0.026278,1
12,0.001697,0.000430,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001444,0.000160,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.048283,0.003872,0.005971,0.000417,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.839686,0.772885,0.833846,0.803559,0.838346,0.817664,0.025995,13
15,0.414024,0.015465,0.019569,0.000800,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858443,0.783273,0.863245,0.827062,0.838911,0.834187,0.028629,2
16,0.053527,0.010489,0.005891,0.000817,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.855053,0.762654,0.836132,0.811779,0.829990,0.819122,0.031436,11
17,0.437306,0.010874,0.019124,0.000881,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859529,0.777541,0.854115,0.830591,0.841991,0.832753,0.029366,6
18,0.001638,0.000558,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001520,0.000146,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.058637,0.007864,0.005548,0.000149,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.848489,0.769093,0.838919,0.818583,0.830964,0.821209,0.027842,10
21,0.482977,0.021992,0.019551,0.000946,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857858,0.778654,0.858693,0.826148,0.838768,0.832024,0.029349,8
22,0.053094,0.002291,0.005544,0.000309,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.854413,0.766761,0.831885,0.805249,0.824792,0.816620,0.029473,15
23,0.467212,0.010957,0.019306,0.001346,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861029,0.776636,0.862286,0.827319,0.837029,0.832860,0.031205,5

In [9]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
childer_input=float(input("Chilrend: "))
gender_input=int(input("Enter the Gender 0 or 1:"))
new_input=int(input("Enter smoker 0 or 1:"))

Age: 32
BMI: 45
Chilrend:  2
Enter the Gender 0 or 1: 1
Enter smoker 0 or 1: 2

In [10]:
result=grid.predict([[age_input,bmi_input,childer_input,gender_input,new_input]])
result

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([42036.83676455])